<!-- <footer class="row">
	<div class="large-8-centerd columns">
		<hr>
		<div class="row">
			<div class="large-up-3 medium- small- columns">
				<p>© Copyright no one at all. Go to town.</p>
			</div>
			<div class=" large-up-4 medium-up-4 small- columns">
				<ul class="inline-list right">
					<li>
						<a href="#">Link 1</a>
					</li>
					<li>
						<a href="#">Link 2</a>
					</li>
					<li>
						<a href="#">Link 3</a>
					</li>
					<li>
						<a href="#">Link 4</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer> -->
<footer class="">
<hr>
		<!-- <div class="row"> -->
			<ul class="icon-bar menu expanded ">
				<li class="item line">
				<a href="#" class="" >Home</a>
				</li>
				<li class="item line">
				<p class="copywrite">© «Актёрское агентство» 2015</p>
				</li>
				<li class="item line">
				<a class="" id="facebook"href="#"><label for="facebook">Facebook</label></a>				
				</li>
			</ul>

		<!-- </div> -->
</footer>
<!-- Не трогать тег! он начался в другом файле. -->


<!--
<script type='text/javascript' id="__bs_script__">//<![CDATA[
  document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.10.0.js'><\/script>".replace("HOST", location.hostname));
  //]]></script>
-->
</div>			<!-- end of content -->

</body>
</html>
