<!-- <footer class="row">
	<div class="large-8-centerd columns">
		<hr>
		<div class="row">
			<div class="large-up-3 medium- small- columns">
				<p>© Copyright no one at all. Go to town.</p>
			</div>
			<div class=" large-up-4 medium-up-4 small- columns">
				<ul class="inline-list right">
					<li>
						<a href="#">Link 1</a>
					</li>
					<li>
						<a href="#">Link 2</a>
					</li>
					<li>
						<a href="#">Link 3</a>
					</li>
					<li>
						<a href="#">Link 4</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer> -->
<footer class="">
<hr>
<!-- <selection> -->
	<!-- </selection> -->
		<div class="row">
			<div class=" icon-menu   menu ">
				<!-- <li class=""> -->
				<a href="#" class="item line" ><label class="">Home</label></a>
				<!-- </li> -->
				<!-- <li class=""> -->
				<a href="#" class="item line" ><label class="">Blog</label></a>
				<!-- </li> -->
				<!-- <li class=""> -->
				<a href="#" class="item line" ><label class="">Pricing</label></a>
				<!-- </li> -->
			</div>
			<p class="copywrite">Copywrite not copypwrite © 2015</p>
		</div>
</footer>
<div id="footer">
<script>
	// 	document.write('<script src=js/vendor/' +
	// 		('__proto__' in {} ? 'zepto' : 'jquery') +
	// 		'.js><\/script>')

		$(document).foundation();
		// jQuery(document).ready(function  ($) {


		// 	var doc = document.documentElement;
		// 	doc.setAttribute('data-useragent', navigator.userAgent);
		// });
	</script>	

	<div class="icon-bar three-up">
		<div class="item"></div>
		<a class="item" id="facebook"href="#">
			<label></label>
		</a>
		<div class="item" href="#">
			<label>© «Актёрское агентство» 2015</label>
		</div>
	</div>
</div> <!-- end of footer -->
<!-- Не трогать тег! он начался в другом файле. -->


<!--
<script type='text/javascript' id="__bs_script__">//<![CDATA[
  document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.10.0.js'><\/script>".replace("HOST", location.hostname));
  //]]></script>
-->
</div>			<!-- end of content -->

</body>
</html>
