<!DOCTYPE html>

<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Актёрское агенство</title>
	<link type="text/plain" rel="author" href="../humans.txt" />
	<meta name="keywords" content="Актёрское агентство, актёр, актрисса" />
	<meta name="description" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="icon" 			href="../images/favicon.ico" 	type="images/png" />
	<link rel="shortcut icon" 	href="../images/favicon.ico" 	type="images/png" />
	<link rel="shortcut icon" 	href="../images/x-icon.png" 	type="images/png"/>
	<link rel="stylesheet" href="" type="text/css" media="screen, projection" />
	<link rel="stylesheet" href="../css/foundation.min.css">
	<link rel="stylesheet" href="../css/foundation.css">
	<link rel="stylesheet" href="../css/emoji.css">
	<link rel="stylesheet" href="../css/pictos.css">
	<link rel="stylesheet" href="../css/pictos-ie7.css">
	<link rel="stylesheet" href="../css/pictos-codes.css">
	<link rel="stylesheet" href="../css/pictos-embedded.css">
	<link rel="stylesheet" href="../css/pictos-ie7-codes.css">
	<link rel="stylesheet" href="../css/animation.css">
	<link rel="stylesheet" href="../css/app.css">

	<!-- This is how you would link your custom stylesheet -->
	<link rel="stylesheet" href="css/app.css">

	<!--[if lte IE 7]>
	<link rel="stylesheet" href="http://assets3.insales.ru/assets/1/3972/249732/v_1435057425/build/ie.css" type="text/css" media="screen, projection" />
	<![endif]-->

<!-- <script src="../bower_components/jquery/dist/jquery.js"></script> -->
<script src="../bower_components/jquery/dist/jquery.min.js"></script>
<script src="/bower_components/foundation-sites/dist/foundation.js"></script>
<script src="/bower_components/foundation-sites/dist/foundation.min.js"></script>
<!-- <script src="/bower_components/foundation-sites/js/foundation.core.js"></script> -->
<script src="/bower_components/foundation/js/vendor/modernizr.js"></script>
<!-- <script src="/bower_components/foundation/js/foundation/foundation.reveal.js"></script> -->
<script src="../js/foundation/foundation.tabs.js"></script>
<script src="../js/app.js"></script>
<script src="../js/matter.js"></script>

<!-- End of the headers for CoffeeCup Web Form Builder -->

</head>
<?php
require_once("functions.php");


?>
<body>
<div id="content">                      <!-- beginning of content -->
<?php
include_once("common-top-bar.php");
// include_once("nav-with-logo.php");
// include_once("top-gear.php");
// include_once("center-gear.php");
// include_once("nav.inc");
 ?>












