<!DOCTYPE html>

<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Актёрское агенство</title>
	<link type="text/plain" rel="author" href="../humans.txt" />
	<meta name="keywords" content="Актёрское агентство, актёр, актрисса" />
	<meta name="description" content="" />
	<link rel="icon" href="" type="image/x-icon" />
	<link rel="shortcut icon" href="" type="image/x-icon" />
	<link rel="shortcut icon" type="image/png" href="" />
	<link rel="stylesheet" href="" type="text/css" media="screen, projection" />
	<link rel="stylesheet" href="/css/emoji.css">
	<link rel="stylesheet" href="/css/pictos.css">
	<link rel="stylesheet" href="/css/pictos-ie7.css">
	<link rel="stylesheet" href="/css/pictos-codes.css">
	<link rel="stylesheet" href="/css/pictos-embedded.css">
	<link rel="stylesheet" href="/css/pictos-ie7-codes.css">
	<link rel="stylesheet" href="/css/animation.css">
	<link rel="stylesheet" href="/css/foundation.css">
	<link rel="stylesheet" href="/css/app.css">

	<!-- This is how you would link your custom stylesheet -->
	<link rel="stylesheet" href="css/app.css">




	<script>

	// NOTE: Все скрипты в апп, все вложения - в  хедер.
</script>



	<!--[if lte IE 7]>
	<link rel="stylesheet" href="http://assets3.insales.ru/assets/1/3972/249732/v_1435057425/build/ie.css" type="text/css" media="screen, projection" />
	<![endif]-->
<script>

 </script>
<!-- Start of the headers for CoffeeCup Web Form Builder -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="./addPerson/colorbox/colorbox.css" />
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="js/vendor/modernizr.js"></script>
<script src="js/foundation.min.js"></script>
<script src="../js/foundation.js"></script>
<script src="../js/foundation/foundation.reveal.js"></script>
<script src="../js/jquery.reveal.js"></script>
<script src="js/app.js"></script>
<script src="js/matter.js"></script>

<!-- End of the headers for CoffeeCup Web Form Builder -->

</head>
<?php
require_once("functions.php");


?>
<body>
<div id="content">                      <!-- beginning of content -->
<?php
include_once("common-top-bar.php");
// include_once("nav-with-logo.php");
// include_once("top-gear.php");
// include_once("center-gear.php");
// include_once("nav.inc");
 ?>












